// Fire Emblem: Fortune's Weave classes.
// Sources (retrieved 2026-10-05):
//   - Serenes Forest, https://serenesforest.net/fortunes-weave/classes/growth-rates/ (growths, primary)
//   - Game8, https://game8.co/games/Fire-Emblem-Fortunes-Weave/archives/618974 (growths cross-check, tiers,
//     and the only source for Dancer and Cataphract growths) and /archives/620256 (class list)
//   - fortunesweave.co.uk, https://fortunesweave.co.uk/classes and /classes/<slug> (movement, weapons,
//     exam requirements, flat stat bonuses, promotion links, restrictions)
//   - fortunesweave.co.uk/wiki/mounts (Game8's mount-per-class recommendations -> mountFamilies)
//
// How classes work here, unlike Engage:
//   - Six tiers: PreClass (Commoner/Noble, +0 growths), Beginner, Specialty, Advanced, Master, Divine.
//     Ideal levels: Beginner 5, Specialty 20, Advanced 35, Master 45 (Game8).
//   - Reclassing is by certification exam (license + Renown + weapon/skill ranks), not a fixed
//     promotion tree. promotesFrom/promotesTo are the few path links fortunesweave.co.uk documents;
//     null means undocumented, not "none".
//   - statBonus is the flat stat change applied while in the class (not a base stat).
//   - caps: no source publishes class max stats yet (every class page reads "Not yet documented"),
//     so every caps value is null. No per-character cap modifiers have been reported either,
//     unlike Engage.
//   - mountFamilies comes from Game8's mount recommendations, so it shows which family each
//     class can ride. Empty does not mean the class can't ride: Dragoon, Bau Lord and Elephant
//     Rider are mounted, but no source names their animal.
// Many Spd/Dex disagreements between Serenes Forest and Game8 are swapped values, which suggests
// a column mix-up in one source; Serenes Forest is used throughout and each case is in `note`.

import type { StatBlock } from './stats';

export type ClassTier = 'PreClass' | 'Beginner' | 'Specialty' | 'Advanced' | 'Master' | 'Divine';
export type MountFamily = 'Ornius' | 'Horse' | 'Pegasus' | 'Bau' | 'Elephant';

export type FWClass = {
  name: string;
  tier: ClassTier | null;
  growth: StatBlock;
  statBonus: StatBlock | null;
  caps: StatBlock | null;
  movement: 'foot' | 'mounted' | 'flying' | null;
  mov: number | null;
  weapons: string[];
  requirements: string | null;
  promotesFrom: string[] | null;
  promotesTo: string[] | null;
  mountFamilies: MountFamily[];
  restrictions: string[];
  note?: string;
};

export const classes: FWClass[] = [
  {
    name: 'Noble',
    tier: 'PreClass',
    growth: { hp: 0, str: 0, mag: 0, spd: 0, dex: 0, def: 0, res: 0, lck: 0, cha: 0 },
    statBonus: null,
    caps: null,
    movement: null,
    mov: null,
    weapons: [],
    requirements: null,
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Commoner',
    tier: 'PreClass',
    growth: { hp: 0, str: 0, mag: 0, spd: 0, dex: 0, def: 0, res: 0, lck: 0, cha: 0 },
    statBonus: null,
    caps: null,
    movement: null,
    mov: null,
    weapons: [],
    requirements: null,
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Gladiator',
    tier: 'Beginner',
    growth: { hp: 10, str: 10, mag: 0, spd: 0, dex: 0, def: 0, res: 0, lck: 0, cha: 0 },
    statBonus: { hp: 1, str: 1, mag: 0, spd: 0, dex: 0, def: 0, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 4,
    weapons: ['Sword D', 'Gauntlet D', 'Axe D'],
    requirements: 'Level 5, Renown 1 · Beginner License',
    promotesFrom: null,
    promotesTo: ['Armored Knight', 'Brigand', 'Light Cavalry', 'Myrmidon'],
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Hunter',
    tier: 'Beginner',
    growth: { hp: 10, str: 0, mag: 0, spd: 10, dex: 10, def: 0, res: 0, lck: 0, cha: 0 },
    statBonus: { hp: 0, str: 0, mag: 0, spd: 1, dex: 1, def: 0, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 4,
    weapons: ['Bow D', 'Sword D'],
    requirements: 'Level 5, Renown 1 · Beginner License',
    promotesFrom: null,
    promotesTo: ['Archer'],
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Soldier',
    tier: 'Beginner',
    growth: { hp: 10, str: 5, mag: 0, spd: -5, dex: 5, def: 10, res: 0, lck: 0, cha: 0 },
    statBonus: { hp: 0, str: 1, mag: 0, spd: 0, dex: 0, def: 1, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 4,
    weapons: ['Spear D', 'Sword', 'Axe D'],
    requirements: 'Level 5, Renown 1 · Beginner License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Ornius Rider',
    tier: 'Beginner',
    growth: { hp: 10, str: 0, mag: 0, spd: 10, dex: 0, def: 0, res: 5, lck: 5, cha: 0 },
    statBonus: { hp: 0, str: 0, mag: 0, spd: 3, dex: 1, def: 0, res: 0, lck: 1, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 5,
    weapons: ['Spear D', 'Sword', 'Axe D'],
    requirements: 'Level 5, Renown 1 · Beginner License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Ornius'],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: dex 0 (Game8 5).',
  },
  {
    name: 'Diviner',
    tier: 'Beginner',
    growth: { hp: 5, str: -5, mag: 15, spd: 0, dex: 5, def: -5, res: 10, lck: 0, cha: 0 },
    statBonus: { hp: 0, str: 0, mag: 1, spd: 0, dex: 0, def: 0, res: 1, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 4,
    weapons: ['Sword', 'Gauntlet', 'Axe', 'White Magic D', 'Black Magic D'],
    requirements: 'Level 5, Renown 1 · Beginner License',
    promotesFrom: null,
    promotesTo: ['Priest', 'Shaman'],
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Myrmidon',
    tier: 'Specialty',
    growth: { hp: 10, str: 0, mag: 0, spd: 15, dex: 10, def: 0, res: 0, lck: 5, cha: 5 },
    statBonus: { hp: 1, str: 0, mag: 0, spd: 2, dex: 0, def: 0, res: -1, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Spear', 'Sword C'],
    requirements: 'Requires Sword C · Level 20, Renown 4 · Specialty License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Brigand',
    tier: 'Specialty',
    growth: { hp: 15, str: 15, mag: -5, spd: 5, dex: 0, def: 5, res: 0, lck: 0, cha: 5 },
    statBonus: { hp: 3, str: 2, mag: 0, spd: 0, dex: 0, def: 1, res: -1, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Sword C', 'Gauntlet', 'Axe C'],
    requirements: 'Requires Axe C, Sword C · Level 20, Renown 4 · Specialty License',
    promotesFrom: ['Gladiator'],
    promotesTo: ['Warrior'],
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Pugilist',
    tier: 'Specialty',
    growth: { hp: 15, str: 10, mag: -5, spd: 10, dex: 5, def: 10, res: 0, lck: 0, cha: 5 },
    statBonus: { hp: 2, str: 1, mag: 0, spd: 1, dex: 0, def: 2, res: -1, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Gauntlet C'],
    requirements: 'Requires Gauntlet C · Level 20, Renown 4 · Specialty License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Archer',
    tier: 'Specialty',
    growth: { hp: 10, str: 0, mag: 0, spd: 10, dex: 15, def: 5, res: 0, lck: 5, cha: 5 },
    statBonus: { hp: 0, str: 0, mag: 0, spd: 2, dex: 2, def: 1, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Bow C'],
    requirements: 'Requires Bow C · Level 20, Renown 4 · Specialty License',
    promotesFrom: ['Hunter'],
    promotesTo: ['Forest Knight', 'Sniper'],
    mountFamilies: [],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: str 0 (Game8 5), dex 15 (Game8 10).',
  },
  {
    name: 'Rogue',
    tier: 'Specialty',
    growth: { hp: 10, str: 0, mag: 0, spd: 15, dex: 10, def: 0, res: 5, lck: 5, cha: 0 },
    statBonus: { hp: 0, str: 0, mag: 0, spd: 3, dex: 1, def: 0, res: 1, lck: 1, cha: -1 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Bow C', 'Sword C'],
    requirements: 'Requires Bow C, Sword C · Level 20, Renown 4 · Specialty License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Armored Knight',
    tier: 'Specialty',
    growth: { hp: 10, str: 10, mag: -5, spd: -5, dex: 5, def: 25, res: -5, lck: 0, cha: 5 },
    statBonus: { hp: 2, str: 1, mag: 0, spd: -2, dex: 0, def: 4, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: null,
    mov: null,
    weapons: ['Spear C', 'Sword', 'Axe C'],
    requirements: 'Requires Heavy E+, Axe C, Spear C · Level 20, Renown 4 · Specialty License',
    promotesFrom: ['Gladiator'],
    promotesTo: ['Dreadnought'],
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Light Cavalry',
    tier: 'Specialty',
    growth: { hp: 10, str: 5, mag: -5, spd: 5, dex: 0, def: 5, res: 0, lck: 5, cha: 10 },
    statBonus: { hp: 1, str: 1, mag: 0, spd: 1, dex: 0, def: 2, res: 0, lck: 0, cha: 1 },
    caps: null,
    movement: 'mounted',
    mov: 6,
    weapons: ['Spear C', 'Sword C', 'Axe'],
    requirements: 'Requires Rider D, Spear C, Sword C · Level 20, Renown 4 · Specialty License',
    promotesFrom: ['Gladiator', 'Ornius Rider'],
    promotesTo: ['Bardinger'],
    mountFamilies: ['Horse'],
    restrictions: [],
  },
  {
    name: 'Charioteer',
    tier: 'Specialty',
    growth: { hp: 10, str: 5, mag: -5, spd: -5, dex: 15, def: 10, res: 0, lck: 5, cha: 10 },
    statBonus: { hp: 3, str: 1, mag: 0, spd: -2, dex: 3, def: 3, res: 0, lck: 0, cha: 1 },
    caps: null,
    movement: 'mounted',
    mov: 5,
    weapons: ['Bow C'],
    requirements: 'Requires Rider D, Bow C · Level 20, Renown 4 · Specialty License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
    note: 'Class ability Charioteer\'s Path raises growths at higher levels; see CHARIOTEERS_PATH in modifiers.ts. Mov 5 per fortunesweave.co.uk; Game8 says 6.',
  },
  {
    name: 'Armored Ornius Rider',
    tier: 'Specialty',
    growth: { hp: 10, str: 0, mag: -5, spd: 10, dex: 5, def: 10, res: 0, lck: 5, cha: 5 },
    statBonus: { hp: 1, str: 0, mag: 0, spd: 2, dex: 0, def: 2, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 6,
    weapons: ['Spear C', 'Sword', 'Axe C'],
    requirements: 'Requires Rider D, Axe C, Spear C · Level 20, Renown 4 · Specialty License',
    promotesFrom: ['Ornius Rider'],
    promotesTo: ['Dragoon'],
    mountFamilies: ['Ornius'],
    restrictions: [],
  },
  {
    name: 'Wing Soldier',
    tier: 'Specialty',
    growth: { hp: 10, str: 0, mag: 5, spd: 0, dex: 5, def: 5, res: 5, lck: 5, cha: 10 },
    statBonus: { hp: 0, str: 0, mag: 0, spd: 4, dex: 1, def: 1, res: 2, lck: 0, cha: 1 },
    caps: null,
    movement: 'flying',
    mov: 6,
    weapons: ['Spear C', 'Sword C'],
    requirements: 'Requires Flier D, Spear C, Sword C · Level 20, Renown 4 · Specialty License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Pegasus'],
    restrictions: ['Female characters only (fortunesweave.co.uk; single source).'],
  },
  {
    name: 'Shaman',
    tier: 'Specialty',
    growth: { hp: 5, str: -5, mag: 15, spd: 10, dex: 10, def: -10, res: 10, lck: 10, cha: 0 },
    statBonus: { hp: 0, str: 0, mag: 2, spd: 1, dex: 1, def: 0, res: 2, lck: 0, cha: -1 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Sword', 'Gauntlet', 'White Magic', 'Black Magic C'],
    requirements: 'Requires Black Magic C · Level 20, Renown 4 · Specialty License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Priest',
    tier: 'Specialty',
    growth: { hp: 5, str: -5, mag: 10, spd: 5, dex: 5, def: -10, res: 15, lck: 15, cha: 10 },
    statBonus: { hp: 0, str: 0, mag: 1, spd: 0, dex: 0, def: 0, res: 3, lck: 2, cha: 1 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Gauntlet', 'Axe', 'White Magic C', 'Black Magic'],
    requirements: 'Requires White Magic C · Level 20, Renown 4 · Specialty License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Shido',
    tier: 'Advanced',
    growth: { hp: 10, str: 5, mag: 0, spd: 15, dex: 10, def: 0, res: -5, lck: 5, cha: 5 },
    statBonus: { hp: 3, str: 0, mag: 0, spd: 7, dex: 3, def: 0, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Spear', 'Sword B'],
    requirements: 'Requires Sword B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Warrior',
    tier: 'Advanced',
    growth: { hp: 20, str: 20, mag: -5, spd: 0, dex: 0, def: 5, res: -5, lck: 0, cha: 5 },
    statBonus: { hp: 4, str: 4, mag: 0, spd: 1, dex: 0, def: 0, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Sword B', 'Gauntlet B', 'Axe B'],
    requirements: 'Requires Gauntlet B, Axe B, Sword B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Blacksmith',
    tier: 'Advanced',
    growth: { hp: 15, str: 10, mag: 10, spd: 0, dex: 5, def: 10, res: 10, lck: 0, cha: 5 },
    statBonus: { hp: 5, str: 1, mag: 1, spd: 1, dex: 0, def: 3, res: 1, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Axe C', 'Black Magic D'],
    requirements: null,
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Unlock: Dietrich\'s route: Do 10 combat art upgrades, then talk to the temple receptionist at the Temple of Smyrnos'],
  },
  {
    name: 'Sniper',
    tier: 'Advanced',
    growth: { hp: 10, str: 5, mag: 0, spd: 10, dex: 20, def: 5, res: 5, lck: 5, cha: 5 },
    statBonus: { hp: 1, str: 0, mag: 0, spd: 5, dex: 5, def: 0, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Bow B'],
    requirements: 'Requires Bow B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Forest Knight',
    tier: 'Advanced',
    growth: { hp: 10, str: 5, mag: 0, spd: 10, dex: 10, def: 5, res: 5, lck: 5, cha: 5 },
    statBonus: { hp: 1, str: 0, mag: 0, spd: 5, dex: 2, def: 1, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 6,
    weapons: ['Bow B', 'Sword'],
    requirements: 'Requires Rider D, Bow B · Level 35, Renown 8 · Advanced License',
    promotesFrom: ['Archer'],
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
  },
  {
    name: 'Ranger',
    tier: 'Advanced',
    growth: { hp: 10, str: 5, mag: 0, spd: 15, dex: 15, def: 0, res: 10, lck: 15, cha: 0 },
    statBonus: { hp: 1, str: 0, mag: 0, spd: 7, dex: 4, def: 0, res: 1, lck: 1, cha: -1 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Bow B', 'Sword B'],
    requirements: 'Requires Bow B, Sword B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Unlock: Dietrich\'s route: Clear Oko\'s challenge (Renown 10) Leda\'s route: Clear the fourth \'new product\' tavern show'],
  },
  {
    name: 'Guardian',
    tier: 'Advanced',
    growth: { hp: 10, str: 10, mag: 0, spd: 0, dex: 5, def: 10, res: 15, lck: 5, cha: 5 },
    statBonus: { hp: 3, str: 1, mag: 0, spd: 1, dex: 0, def: 3, res: 4, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Spear B', 'White Magic'],
    requirements: 'Requires Spear B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Unlock: Dietrich\'s route: Clear Il-Lara\'s challenge (Renown 6) Theodora\'s route: Clear the Roca battalion boost'],
  },
  {
    name: 'Dreadnought',
    tier: 'Advanced',
    growth: { hp: 15, str: 15, mag: -5, spd: -10, dex: 5, def: 30, res: -10, lck: 0, cha: 5 },
    statBonus: { hp: 5, str: 3, mag: 0, spd: -5, dex: 0, def: 9, res: -1, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 4,
    weapons: ['Spear B', 'Axe B'],
    requirements: 'Requires Heavy D, Axe B, Spear B · Level 35, Renown 8 · Advanced License',
    promotesFrom: ['Armored Knight'],
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Bardinger',
    tier: 'Advanced',
    growth: { hp: 10, str: 10, mag: -5, spd: 0, dex: 0, def: 5, res: 10, lck: 5, cha: 10 },
    statBonus: { hp: 3, str: 0, mag: 0, spd: 1, dex: 0, def: 1, res: 0, lck: 0, cha: 3 },
    caps: null,
    movement: 'mounted',
    mov: 6,
    weapons: ['Spear C', 'Sword B', 'Axe'],
    requirements: 'Requires Rider C, Sword B, Spear C · Level 35, Renown 8 · Advanced License',
    promotesFrom: ['Light Cavalry'],
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
  },
  {
    name: 'Elephant Rider',
    tier: 'Advanced',
    growth: { hp: 20, str: 10, mag: -5, spd: -10, dex: 20, def: 15, res: -5, lck: 5, cha: 10 },
    statBonus: { hp: 10, str: 2, mag: 0, spd: -5, dex: 3, def: 7, res: 0, lck: 0, cha: 3 },
    caps: null,
    movement: 'mounted',
    mov: 5,
    weapons: [],
    requirements: 'Requires Rider C · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: spd -10 (Game8 20), dex 20 (Game8 -10).',
  },
  {
    name: 'Caladrius',
    tier: 'Advanced',
    growth: { hp: 15, str: 0, mag: 10, spd: 10, dex: 5, def: 10, res: 10, lck: 5, cha: 5 },
    statBonus: { hp: 2, str: 0, mag: 1, spd: 3, dex: 0, def: 1, res: 2, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: null,
    weapons: ['Spear', 'Sword', 'Axe', 'Black Magic B'],
    requirements: 'Requires Rider D, Black Magic B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Ornius'],
    restrictions: ['Unlock: Cai\'s route: Clear Castor\'s training request (Renown 7)'],
    note: 'Sources disagree, Serenes Forest used: spd 10 (Game8 5), dex 5 (Game8 10).',
  },
  {
    name: 'Dragoon',
    tier: 'Advanced',
    growth: { hp: 15, str: 5, mag: 0, spd: 5, dex: 0, def: 10, res: 10, lck: 10, cha: 5 },
    statBonus: { hp: 2, str: 1, mag: 0, spd: 3, dex: 1, def: 1, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 6,
    weapons: ['Spear B', 'Sword', 'Axe B'],
    requirements: 'Requires Flier C, Axe B, Spear B · Level 35, Renown 8 · Advanced License',
    promotesFrom: ['Armored Ornius Rider', 'Wing Soldier'],
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Unlock: Cai\'s route: Clear Aurora\'s training request (Renown 8) Theodora\'s route: Clear the Rilfish battalion boost'],
    note: 'Sources disagree, Serenes Forest used: spd 5 (Game8 0), dex 0 (Game8 5).',
  },
  {
    name: 'Ovate',
    tier: 'Advanced',
    growth: { hp: 10, str: -5, mag: 20, spd: 5, dex: 15, def: -10, res: 15, lck: 10, cha: 0 },
    statBonus: { hp: 1, str: 0, mag: 4, spd: 3, dex: 4, def: 0, res: 4, lck: 0, cha: -1 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Sword', 'Gauntlet', 'White Magic', 'Black Magic B'],
    requirements: 'Requires Black Magic B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Bishop',
    tier: 'Advanced',
    growth: { hp: 10, str: -5, mag: 15, spd: 0, dex: 5, def: -10, res: 20, lck: 20, cha: 10 },
    statBonus: { hp: 1, str: 0, mag: 3, spd: 1, dex: 0, def: 0, res: 5, lck: 3, cha: 3 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Gauntlet', 'Axe', 'White Magic B', 'Black Magic'],
    requirements: 'Requires White Magic B · Level 35, Renown 8 · Advanced License',
    promotesFrom: ['Priest'],
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: dex 5 (Game8 0).',
  },
  {
    name: 'Troubadour',
    tier: 'Advanced',
    growth: { hp: 10, str: 0, mag: 15, spd: 0, dex: 5, def: 5, res: 15, lck: 15, cha: 10 },
    statBonus: { hp: 0, str: 0, mag: 1, spd: 1, dex: 1, def: 1, res: 2, lck: 0, cha: 3 },
    caps: null,
    movement: 'mounted',
    mov: 6,
    weapons: ['White Magic B', 'Black Magic B'],
    requirements: 'Requires Rider D, White Magic B, Black Magic B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: ['Unlock: Cai\'s route: Clear Bertrand\'s training request (Renown 10) Leda\'s route: Clear the fourth \'new product\' tavern show'],
    note: 'Sources disagree, Serenes Forest used: spd 0 (Game8 5), dex 5 (Game8 0).',
  },
  {
    name: 'Swordmaster',
    tier: 'Master',
    growth: { hp: 15, str: 10, mag: 0, spd: 20, dex: 15, def: 0, res: 0, lck: 5, cha: 5 },
    statBonus: { hp: 5, str: 2, mag: 0, spd: 7, dex: 7, def: 0, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Spear', 'Sword A'],
    requirements: 'Requires Sword A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
    note: 'fortunesweave.co.uk spells it "Sword Master".',
  },
  {
    name: 'High Savant',
    tier: 'Master',
    growth: { hp: 10, str: 15, mag: 15, spd: 10, dex: 5, def: 5, res: 5, lck: 5, cha: 5 },
    statBonus: { hp: 5, str: 2, mag: 2, spd: 3, dex: 3, def: 2, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 7,
    weapons: ['Sword B', 'Black Magic D'],
    requirements: 'Requires Rider D, Black Magic D, Sword B · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
  },
  {
    name: 'Battlemaster',
    tier: 'Master',
    growth: { hp: 25, str: 25, mag: -5, spd: 5, dex: -5, def: 10, res: -5, lck: -5, cha: 5 },
    statBonus: { hp: 13, str: 6, mag: 0, spd: 2, dex: 0, def: 4, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Sword A', 'Gauntlet A', 'Axe A'],
    requirements: 'Requires Gauntlet A, Axe A, Sword A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: spd 5 (Game8 -5), dex -5 (Game8 5).',
  },
  {
    name: 'War Monk',
    tier: 'Master',
    growth: { hp: 15, str: 10, mag: 0, spd: 15, dex: 0, def: 5, res: 15, lck: 5, cha: 5 },
    statBonus: { hp: 5, str: 2, mag: 0, spd: 5, dex: 2, def: 2, res: 4, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Gauntlet B', 'White Magic D'],
    requirements: 'Requires White Magic D, Gauntlet B · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Bow Adept',
    tier: 'Master',
    growth: { hp: 15, str: 5, mag: 0, spd: 15, dex: 20, def: 5, res: 5, lck: 5, cha: 5 },
    statBonus: { hp: 4, str: 2, mag: 0, spd: 5, dex: 9, def: 0, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Bow A'],
    requirements: 'Requires Bow A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Bow Knight',
    tier: 'Master',
    growth: { hp: 10, str: 10, mag: 0, spd: 15, dex: 10, def: 5, res: 0, lck: 5, cha: 5 },
    statBonus: { hp: 3, str: 2, mag: 0, spd: 7, dex: 5, def: 2, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 7,
    weapons: ['Bow A', 'Sword'],
    requirements: 'Requires Rider D, Bow A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
  },
  {
    name: 'Shadow Seeker',
    tier: 'Master',
    growth: { hp: 15, str: 5, mag: 0, spd: 25, dex: 15, def: 0, res: 10, lck: 15, cha: 0 },
    statBonus: { hp: 4, str: 0, mag: 0, spd: 9, dex: 7, def: 0, res: 0, lck: 2, cha: -2 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Bow A', 'Sword A'],
    requirements: 'Requires Bow A, Sword A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: spd 25 (Game8 15), dex 15 (Game8 25).',
  },
  {
    name: 'Sentinel',
    tier: 'Master',
    growth: { hp: 15, str: 15, mag: 0, spd: 5, dex: 5, def: 10, res: 15, lck: 5, cha: 5 },
    statBonus: { hp: 5, str: 4, mag: 0, spd: 2, dex: 4, def: 4, res: 5, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Spear A', 'White Magic'],
    requirements: 'Requires Spear A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Castle Knight',
    tier: 'Master',
    growth: { hp: 25, str: 20, mag: -5, spd: -15, dex: 5, def: 30, res: -10, lck: 0, cha: 5 },
    statBonus: { hp: 9, str: 6, mag: 0, spd: -6, dex: 4, def: 13, res: -2, lck: 0, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 4,
    weapons: ['Spear A', 'Axe A'],
    requirements: 'Requires Heavy C, Axe A, Spear A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Orichaldia',
    tier: 'Master',
    growth: { hp: 15, str: 15, mag: -5, spd: 5, dex: 0, def: 5, res: 5, lck: 5, cha: 10 },
    statBonus: { hp: 7, str: 3, mag: 0, spd: 2, dex: 3, def: 2, res: 0, lck: 0, cha: 2 },
    caps: null,
    movement: 'mounted',
    mov: 7,
    weapons: ['Spear A', 'Sword A', 'Axe'],
    requirements: 'Requires Rider B, Spear A, Sword A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: spd 5 (Game8 0), dex 0 (Game8 5).',
  },
  {
    name: 'Great Knight',
    tier: 'Master',
    growth: { hp: 20, str: 20, mag: -5, spd: -10, dex: 0, def: 15, res: -10, lck: 0, cha: 5 },
    statBonus: { hp: 12, str: 5, mag: 0, spd: -4, dex: 2, def: 5, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 6,
    weapons: ['Spear A', 'Sword', 'Axe A'],
    requirements: 'Requires Heavy D, Rider D, Axe A, Spear A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
  },
  {
    name: 'Celestial Trooper',
    tier: 'Master',
    growth: { hp: 15, str: 5, mag: -5, spd: 10, dex: 5, def: 5, res: 15, lck: 15, cha: 10 },
    statBonus: { hp: 3, str: 0, mag: 0, spd: 5, dex: 3, def: 0, res: 5, lck: 0, cha: 2 },
    caps: null,
    movement: 'mounted',
    mov: 7,
    weapons: ['Spear A', 'Sword A'],
    requirements: 'Requires Flier C, Spear A, Sword A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Pegasus'],
    restrictions: [],
  },
  {
    name: 'Bau Lord',
    tier: 'Master',
    growth: { hp: 15, str: 5, mag: 0, spd: 5, dex: 0, def: 10, res: 10, lck: 10, cha: 5 },
    statBonus: { hp: 5, str: 2, mag: 0, spd: 3, dex: 3, def: 3, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 7,
    weapons: ['Spear A', 'Sword', 'Axe A'],
    requirements: 'Requires Flier C, Axe A, Spear A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
  },
  {
    name: 'Druid',
    tier: 'Master',
    growth: { hp: 10, str: -5, mag: 30, spd: 10, dex: 15, def: -10, res: 20, lck: 10, cha: 0 },
    statBonus: { hp: 4, str: 0, mag: 7, spd: 4, dex: 7, def: 0, res: 5, lck: 0, cha: -2 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Sword', 'Gauntlet', 'Black Magic A'],
    requirements: 'Requires Black Magic A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: spd 10 (Game8 15), dex 15 (Game8 10).',
  },
  {
    name: 'Wiseman',
    tier: 'Master',
    growth: { hp: 10, str: -5, mag: 20, spd: 5, dex: 0, def: -10, res: 25, lck: 20, cha: 10 },
    statBonus: { hp: 4, str: 0, mag: 5, spd: 2, dex: 2, def: 0, res: 9, lck: 4, cha: 2 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Gauntlet', 'Axe', 'White Magic A'],
    requirements: 'Requires White Magic A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: [],
    note: 'Sources disagree, Serenes Forest used: spd 5 (Game8 0), dex 0 (Game8 5).',
  },
  {
    name: 'Valkyrium',
    tier: 'Master',
    growth: { hp: 10, str: 0, mag: 15, spd: 5, dex: 5, def: 5, res: 10, lck: 15, cha: 10 },
    statBonus: { hp: 2, str: 0, mag: 2, spd: 2, dex: 3, def: 2, res: 3, lck: 0, cha: 2 },
    caps: null,
    movement: 'mounted',
    mov: 7,
    weapons: ['White Magic A', 'Black Magic A'],
    requirements: 'Requires Rider D, White Magic A, Black Magic A · Level 45 · Master License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: [],
  },
  {
    name: 'The Blade',
    tier: 'Divine',
    growth: { hp: 15, str: 10, mag: 10, spd: 20, dex: 20, def: 5, res: 5, lck: 5, cha: 10 },
    statBonus: { hp: 7, str: 4, mag: 4, spd: 7, dex: 7, def: 0, res: 0, lck: 0, cha: 2 },
    caps: null,
    movement: 'foot',
    mov: 6,
    weapons: ['Spear', 'Sword'],
    requirements: 'Requires Sword S · Demonic Swordguard',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
  },
  {
    name: 'The Apsara',
    tier: 'Divine',
    growth: { hp: 15, str: 5, mag: 10, spd: 25, dex: 15, def: 5, res: 5, lck: 10, cha: 30 },
    statBonus: { hp: 5, str: 2, mag: 4, spd: 7, dex: 5, def: 0, res: 0, lck: 0, cha: 9 },
    caps: null,
    movement: 'foot',
    mov: 6,
    weapons: ['Bow', 'Sword'],
    requirements: 'Requires Bow C, Sword A · Muses\' Necklace',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
  },
  {
    name: 'The Eternal',
    tier: 'Divine',
    growth: { hp: 30, str: 30, mag: 0, spd: 10, dex: 0, def: 15, res: 0, lck: 0, cha: 10 },
    statBonus: { hp: 12, str: 6, mag: 0, spd: 2, dex: 1, def: 5, res: 0, lck: 0, cha: 2 },
    caps: null,
    movement: 'foot',
    mov: 6,
    weapons: ['Sword', 'Gauntlet', 'Axe'],
    requirements: 'Requires Gauntlet S, Axe S, Sword S · Scales of Judgement',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
    note: 'Sources disagree, Serenes Forest used: cha 10 (Game8 0).',
  },
  {
    name: 'The Godhand',
    tier: 'Divine',
    growth: { hp: 15, str: 10, mag: 10, spd: 15, dex: 5, def: 10, res: 15, lck: 5, cha: 10 },
    statBonus: { hp: 7, str: 4, mag: 4, spd: 5, dex: 2, def: 4, res: 5, lck: 0, cha: 2 },
    caps: null,
    movement: 'foot',
    mov: 6,
    weapons: ['Gauntlet', 'White Magic'],
    requirements: 'Requires White Magic C, Gauntlet S · Emperor\'s Sash',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
  },
  {
    name: 'The Calamity',
    tier: 'Divine',
    growth: { hp: 15, str: 5, mag: 15, spd: 25, dex: 20, def: 5, res: 15, lck: 15, cha: 5 },
    statBonus: { hp: 5, str: 2, mag: 4, spd: 7, dex: 5, def: 0, res: 4, lck: 4, cha: 0 },
    caps: null,
    movement: 'foot',
    mov: 6,
    weapons: ['Bow', 'Sword'],
    requirements: 'Requires Bow S, Sword S · Crystal of Darkness',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
  },
  {
    name: 'The Trident',
    tier: 'Divine',
    growth: { hp: 15, str: 15, mag: 5, spd: 10, dex: 10, def: 15, res: 15, lck: 5, cha: 10 },
    statBonus: { hp: 7, str: 4, mag: 4, spd: 2, dex: 4, def: 5, res: 5, lck: 0, cha: 2 },
    caps: null,
    movement: 'foot',
    mov: 6,
    weapons: ['Spear', 'White Magic'],
    requirements: 'Requires Spear S · Trident',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
  },
  {
    name: 'The Cavalier',
    tier: 'Divine',
    growth: { hp: 20, str: 15, mag: 5, spd: 10, dex: 10, def: 15, res: 10, lck: 5, cha: 15 },
    statBonus: { hp: 11, str: 3, mag: 0, spd: 4, dex: 5, def: 5, res: 1, lck: 0, cha: 2 },
    caps: null,
    movement: 'mounted',
    mov: 8,
    weapons: ['Spear', 'Sword', 'Axe'],
    requirements: 'Requires Riding A, Axe S, Spear S, Sword S · Divinium Saddle',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
  },
  {
    name: 'The Avatar',
    tier: 'Divine',
    growth: { hp: 10, str: -5, mag: 30, spd: 10, dex: 5, def: -5, res: 30, lck: 20, cha: 10 },
    statBonus: { hp: 5, str: 0, mag: 9, spd: 2, dex: 2, def: 0, res: 9, lck: 5, cha: 2 },
    caps: null,
    movement: 'foot',
    mov: 6,
    weapons: ['Sword', 'Gauntlet', 'Axe', 'White Magic', 'Black Magic'],
    requirements: 'Requires White Magic S, Black Magic S · Lotus of Reincarnation',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Part 3 only. Needs a one-of-a-kind Divine License item from the Temple of the Diadem, so only one unit can hold this class at a time.'],
  },
  {
    name: 'Dancer',
    tier: 'Advanced',
    growth: { hp: 15, str: 5, mag: 0, spd: 25, dex: 10, def: 0, res: 5, lck: 10, cha: 20 },
    statBonus: { hp: 4, str: 0, mag: 0, spd: 9, dex: 5, def: 0, res: 0, lck: 0, cha: 5 },
    caps: null,
    movement: 'foot',
    mov: 5,
    weapons: ['Bow B', 'Sword B'],
    requirements: 'Requires Bow B, Sword B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: [],
    restrictions: ['Unlock: Leda\'s route: Clear the Part I Chapter 9 sub-quest \'Great Dancer\'s Successor\' (deliver Hingosh to Baina Oasis)'],
    note: 'Not on Serenes Forest; growths from Game8.',
  },
  {
    name: 'Cataphract',
    tier: 'Advanced',
    growth: { hp: 15, str: 15, mag: -5, spd: -10, dex: 0, def: 10, res: -5, lck: 0, cha: 5 },
    statBonus: { hp: 5, str: 2, mag: 0, spd: -1, dex: 0, def: 5, res: 0, lck: 0, cha: 0 },
    caps: null,
    movement: 'mounted',
    mov: 5,
    weapons: ['Spear B', 'Sword', 'Axe B'],
    requirements: 'Requires Heavy E+, Rider D, Axe B, Spear B · Level 35, Renown 8 · Advanced License',
    promotesFrom: null,
    promotesTo: null,
    mountFamilies: ['Horse'],
    restrictions: ['Unlock: Theodora\'s route: Clear every battalion boost available up to the start of Chapter 8'],
    note: 'Not on Serenes Forest; growths from Game8.',
  },
];
